version: '3.10'

services:
  postgres-micro:
    container_name: postgres_service
    build:
      context: services/postgres
      dockerfile: PostgresDockerfile
    env_file:
      - ./.env
    command: -p 5437
    ports:
      - "5437:5437"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d giga -p 5437"]
      interval: 5s
      timeout: 5s
      retries: 10

  micro-chatbot:
    container_name: micro_chatbot
    build:
      context: services/chatbot
      dockerfile: Dockerfile
    command: >
      sh -c "dockerize
      -wait tcp://postgres_service:5437
      -timeout 2m
      -- python ./main.py"
    env_file:
      - services/chatbot/.env
    volumes:
      - ./services/chatbot:/app
    depends_on:
      postgres-micro:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8006"

volumes:
  postgres_data: