version: '3.10'

services:
  postgres-micro:
    container_name: postgres_service
    build:
      context: services/postgres
      dockerfile: PostgresDockerfile
    command: '-p 5437'
    env_file:
      - ./.env
    ports:
      - "5437:5437"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d giga -p 5437"]
      interval: 5s
      timeout: 5s
      retries: 10

  micro-chatbot:
    container_name: micro_chatbot
    build:
      context: services/chatbot
      dockerfile: Dockerfile
    env_file:
      - services/chatbot/.env
    depends_on:
      postgres-micro:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8006:8006"

  users:
    container_name: micro-users
    build:
      context: services/users
      dockerfile: Dockerfile
    env_file:
      - services/users/.env
    depends_on:
      postgres-micro:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8005:8005"

volumes:
  postgres_data: